spring:
  cloud:
    gateway:
      routes:
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/api/chat/**
          filters:
            - StripPrefix=1
        # ... other routes ... 